[general]
#import = [ "~/.config/alacritty/themes/themes/alabaster_dark.toml" ]
#import = [ "~/.config/alacritty/themes/themes/smoooooth.toml" ]
import = [ "~/.config/alacritty/themes/themes/catppuccin.toml" ]

live_config_reload = true

[env]
term = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }
blur = true
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
resize_increments = true

[scrolling]
history = 10000
multiplier = 4

[font]
normal = { family = "IosevkaTerm Nerd Font Propo", style = "Medium" }
bold = { style = "Bold" }
size = 10.5
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Never" }
unfocused_hollow = false
thickness = 0.25

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "Paste" },
]
